### ISSUE TITLE
issue with python 3?

### ISSUE THREAD

**Issue by raw937** [osfclient/osfclient#174]
Traceback (most recent call last):
  File "/home/richard.white3/.conda/envs/py3.6/bin/osf", line 8, in <module>
    sys.exit(main())
  File "/home/richard.white3/.conda/envs/py3.6/lib/python3.8/site-packages/osfclient/__main__.py", line 104, in main
    exit_code = args.func(args)
  File "/home/richard.white3/.conda/envs/py3.6/lib/python3.8/site-packages/osfclient/cli.py", line 91, in wrapper
    return_value = f(cli_args)
  File "/home/richard.white3/.conda/envs/py3.6/lib/python3.8/site-packages/osfclient/cli.py", line 218, in list_
    project = osf.project(args.project)
  File "/home/richard.white3/.conda/envs/py3.6/lib/python3.8/site-packages/osfclient/api.py", line 24, in project
    return Project(self._json(self._get(url), 200), self.session)
  File "/home/richard.white3/.conda/envs/py3.6/lib/python3.8/site-packages/osfclient/models/core.py", line 58, in _json
    raise RuntimeError("Response has status "
RuntimeError: Response has status code 404 not (200,)

**Comment by sappelhoff** [comment]
Looks to me rather like an error with a non-existing page. Have you solved the problem in the meantime?

**Comment by felliott** [comment]
Hey @raw937!

I concur with @sappelhoff, this seems to be a problem with a file not being found rather than a python3 compatibility issue.  I'm going to close this, but please feel free to open a new ticket if the missing file issue is a result of a programming error in `osfclient`.  Thank you!

Cheers,
@felliott

**Comment by itsyuchao** [comment]
Hi, 

While trying to run `osf ls`, I'm having the same RunTimeError and error traceback (also in a conda environment). I'm very new to this and would really appreciate some help!

I have just pip installed osfclient in my conda base environment (which contains python v3.7.6), and ran `osf init` to specify my username and project without a problem. I then ran `osf ls` and typed in my password. However, instead of showing me a list of the current OSF project content, I encountered the same error as @raw937. I have double checked my OSF login info and project name. 

Thanks in advance! 
Yuchao

**Comment by itsyuchao** [comment]
> Hi,
> 
> While trying to run `osf ls`, I'm having the same RunTimeError and error traceback (also in a conda environment). I'm very new to this and would really appreciate some help!
> 
> I have just pip installed osfclient in my conda base environment (which contains python v3.7.6), and ran `osf init` to specify my username and project without a problem. I then ran `osf ls` and typed in my password. However, instead of showing me a list of the current OSF project content, I encountered the same error as @raw937. I have double checked my OSF login info and project name.
> 
> Thanks in advance!
> Yuchao

I realized my previous mistake in using the actual project name rather than the 5 alphanumeric code. Now there is no RunTimeError but `osf ls` does not return anything (I have uploaded files using the Web UI). Could someone point me to a solution here?
