### ISSUE TITLE
do the OSF support revocable authentication tokens?

### ISSUE THREAD

**Issue by ctb** [osfclient/osfclient#99]
I can envision some situations where I don't want to distribute my password but instead want a revokable token that's (e.g.) tied to a specific IP address, duration of time, etc.

**Comment by chartgerink** [comment]
AFAIK, it allows you create personal access tokens in the settings that you can manually revoke, but not automatically, nor can you limit it to IP address.

**Comment by betatim** [comment]
Create a new token: https://osf.io/settings/tokens/create/ with scopes but I think they give full read or full write access to all your projects not just one.

**Comment by icereval** [comment]
e.g. https://github.com/CenterForOpenScience/osf-sync/blob/develop/osfsync/utils/authentication.py#L32

**Comment by betatim** [comment]
@icereval nice! Do you know if there is a plan to have tokens with limited scope in terms of projects?

The usecase I see would be something like allowing a robot (like travis) to access files for a certain project or otherwise share that token in a context where you wouldn't want to share (even in encrypted form) something that gives access to all your projects.

**Comment by DimitriPapadopoulos** [comment]
@ctb Have you opened an issue in [osf.io](https://github.com/CenterForOpenScience/osf.io)?

@betatim Tokens are a good idea indeed, perhaps coupled to a service account for each specific purpose. For each specific purpose you create a service account with the desired access rights, project by  project, then a token for each service account. Yet it still won't be possible to tie such a token to an IP address or a duration of time.

As an example I have myself created an service account to mass upload files to an OSF project. I will give this account write access only to the specific project I want to upload to. Additionally I have created this account with a username/password since _osfclient_ doesn't support tokens or OAuth yet.

**Comment by felliott** [comment]
This should be fixed in the next release, which I am preparing now.

**Comment by felliott** [comment]
This has been merged into `master` and released in `osfclient==0.0.5`. Thank you, @ctb!
